#!/usr/bin/env python3
"""
Cleanup redundant Sony bracketed photos after Lightroom HDR merge.

This script uses the groups.txt file generated by `group_sony_bracketed_photos.py`
to detect bracketed exposures, and safely removes the redundant
(over- and under-exposed) RAW files.

Usage:
    python cleanup_sony_bracketed_photos.py --groups /path/to/groups.txt
"""

import argparse
import os
import shutil
from exiftool import ExifToolHelper
from tqdm import tqdm


ATTRIBUTES = [
    "SourceFile",
    "EXIF:ExposureCompensation",
    "MakerNotes:SequenceImageNumber",
    "MakerNotes:SequenceLength",
]


def parse_groups_file(path):
    """Parse groups.txt into a list of groups (list of file paths)."""
    groups = []
    current = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            if line.startswith("#group"):
                if current:
                    groups.append(current)
                    current = []
            else:
                current.append(line)
        if current:
            groups.append(current)
    return groups


def load_metadata(files):
    """Load metadata for a list of files via ExifTool (with tqdm)."""
    metadata = []
    with ExifToolHelper() as et:
        for file in tqdm(files, desc="Reading metadata", unit="file"):
            metadata.extend(et.get_metadata([file]))
    filtered = {item["SourceFile"]: {k: item.get(k) for k in ATTRIBUTES} for item in metadata}
    return filtered


def detect_properly_exposed(group, metadata):
    """
    Detect the properly exposed file in the group based on ExposureCompensation.
    Uses the median exposure value from the sequence.
    """
    seq_lengths = {metadata[f].get("MakerNotes:SequenceLength") for f in group}
    if len(seq_lengths) != 1 or list(seq_lengths)[0] != len(group):
        print(f"Warning: Group length mismatch in {os.path.basename(group[0])}. Skipping.")
        return None

    if len(group) % 2 == 0:
        print(f"Warning: Even number of frames in {os.path.basename(group[0])} (expected odd). Skipping.")
        return None

    exposures = [(f, metadata[f]["EXIF:ExposureCompensation"]) for f in group]
    if any(ev is None for _, ev in exposures):
        print(f"Warning: Missing exposure compensation in group {os.path.basename(group[0])}. Skipping.")
        return None

    exposures.sort(key=lambda x: x[1])
    median_index = len(exposures) // 2
    candidate = exposures[median_index][0]
    return candidate


def expected_hdr_file(group):
    """
    Lightroom Classic creates HDR DNG named after one of the source files (usually first).
    We'll check all possible base names in the group.
    """
    parent_dir = os.path.dirname(group[0])
    base_names = [os.path.splitext(os.path.basename(f))[0] for f in group]
    for base in base_names:
        candidate = os.path.join(parent_dir, f"{base}-HDR.dng")
        if os.path.exists(candidate):
            return candidate
    return None


def move_or_delete_files(group, keep_file, action, safety_dir, dry_run=False):
    """Remove redundant files: either move them to safety_dir, delete them, or just show in dry-run."""
    moved = []
    for f in group:
        if f == keep_file:
            continue
        dest = os.path.join(safety_dir, os.path.basename(f))
        moved.append(f)
        if dry_run:
            if action == "move":
                print(f"Would move: {f} -> {dest}")
            elif action == "delete":
                print(f"Would delete: {f}")
        else:
            if action == "move":
                os.makedirs(safety_dir, exist_ok=True)
                shutil.move(f, dest)
            elif action == "delete":
                os.remove(f)
    return moved


def main():
    parser = argparse.ArgumentParser(description="Remove redundant Sony bracketed photos after Lightroom HDR merge.")
    parser.add_argument("--groups", required=True, help="Path to groups.txt generated by group_sony_bracketed_photos.py")
    parser.add_argument(
        "--action",
        choices=["move", "delete"],
        default="move",
        help="Whether to move redundant files to a safety folder (default) or permanently delete them.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Show which files would be moved/deleted without actually performing the action.",
    )
    args = parser.parse_args()

    groups = parse_groups_file(args.groups)
    if not groups:
        print("No groups found in file.")
        return

    all_files = [f for g in groups for f in g]
    metadata = load_metadata(all_files)

    total_processed = 0
    total_removed = 0
    warnings = 0

    print("Processing groups...")
    if args.dry_run:
        print("Running in dry run mode, so no changes would be applied.")    
    for group in groups:
        hdr_file = expected_hdr_file(group)
        if not hdr_file:
            print(f"Warning: No HDR DNG found for group starting with {os.path.basename(group[0])}. Skipping.")
            warnings += 1
            continue

        keep_file = detect_properly_exposed(group, metadata)
        if not keep_file:
            warnings += 1
            continue

        parent_dir = os.path.dirname(group[0])
        safety_dir = os.path.join(parent_dir, "_over_under_exposed")

        moved = move_or_delete_files(group, keep_file, args.action, safety_dir, dry_run=args.dry_run)
        total_removed += len(moved)
        total_processed += 1

    print(f"\nDone. Processed {total_processed} groups.")
    print(f"Removed {total_removed} redundant files.")
    if args.action == "move":
        print("Redundant files were moved into '_over_under_exposed' folders.")
    if warnings:
        print(f"{warnings} group(s) skipped due to missing HDR or detection issues.")


if __name__ == "__main__":
    main()
